# =============================================================================
# File   : evaluate.py
# Project: Real-Time Edge AI Video Processor on FPGA
# Purpose: Accuracy report: float model vs integer golden model on the 10,000 MNIST
#          test images, plus a separate, clearly labeled "augmented" test (shifted,
#          rotated, thicker, gray background) as a first look at the domain gap.
#          Writes ml/reports/accuracy.md. Real captured ROI images (Phase 4) get their own row later.
#
# Usage:  .venv\Scripts\python.exe ml/evaluate.py
# =============================================================================
import os

import numpy as np
import torch

import golden_int
from data_utils import augment, load_mnist, to_float
from model import net_from_numpy

HERE = os.path.dirname(os.path.abspath(__file__))
REPORT = os.path.join(HERE, "reports", "accuracy.md")


def float_predict(net, x_float):
    with torch.no_grad():
        return torch.cat([net(x_float[i:i + 2000]).argmax(1) for i in range(0, len(x_float), 2000)]).numpy()


def main():
    net = net_from_numpy(dict(np.load(os.path.join(HERE, "model_float.npz"))))
    q = golden_int.load_params()
    _, _, xte_u8, yte = load_mnist()

    rows = []
    # 1) Clean MNIST test set
    pf = float_predict(net, to_float(xte_u8))
    out = golden_int.infer_batched(xte_u8, q)
    pi = out["digit"]
    rows.append(("MNIST test set (clean), 10,000 images", (pf == yte).mean(), (pi == yte).mean(), (pf == pi).mean()))

    # 2) Augmented MNIST test set (fixed seed): NOT real camera data, only a stress test
    gen = torch.Generator().manual_seed(2024)
    xa = augment(to_float(xte_u8), gen)
    xa_u8 = np.round(xa.squeeze(1).numpy() * 255).astype(np.uint8)
    pfa = float_predict(net, to_float(xa_u8))
    pia = golden_int.infer_batched(xa_u8, q)["digit"]
    rows.append(("MNIST test set, augmented (shift/rotate/scale/thickness/background), 10,000 images",
                 (pfa == yte).mean(), (pia == yte).mean(), (pfa == pia).mean()))

    # Saturation statistics: how often the clamp at 255 is hit (sign of a too small activation scale)
    sat1 = (out["l1"] == 255).mean()
    sat2 = (out["l2"] == 255).mean()
    zero1 = (out["l1"] == 0).mean()
    conf_mean = out["conf"].mean()

    lines = ["# Accuracy report (generated by ml/evaluate.py)", "",
             "| Test set | Float model | Integer golden model | Float/int same prediction |",
             "|---|---|---|---|"]
    for name, a, b, c in rows:
        lines.append(f"| {name} | {a * 100:.2f} % | {b * 100:.2f} % | {c * 100:.2f} % |")
    lines += ["", f"- L1 outputs at 255 (saturated): {sat1 * 100:.4f} %, L2 at 255: {sat2 * 100:.4f} %, L1 at 0 (ReLU): {zero1 * 100:.1f} %",
              f"- Mean confidence value on the clean test set: {conf_mean:.1f} / 255",
              f"- Requantization: M1={int(q['M1'])} S1={int(q['S1'])}, M2={int(q['M2'])} S2={int(q['S2'])}, "
              f"Mc={int(q['MC'])} Sc={int(q['SC'])}",
              "", "The augmented row is a synthetic stress test, not real camera data. "
              "Accuracy on real captured ROI images (Phase 4) and on the board (Phase 7) is reported separately."]
    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with open(REPORT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
