# =============================================================================
# File   : export.py
# Project: Real-Time Edge AI Video Processor on FPGA
# Purpose: Export everything the hardware and its testbenches need into ml/export/:
#   Weights (committed; $readmemh text files, one value per line):
#     l1_w.mem (72 x int8)   l1_b.mem (8 x int32)
#     l2_w.mem (1152 x int8) l2_b.mem (16 x int32)
#     fc_w.mem (4000 x int8) fc_b.mem (10 x int32)
#     quant_params.svh       requantization constants M1,S1,M2,S2,MC,SC as localparams
#   Test vectors, ONE IMAGE PER LINE as a long hex string ($readmemh with wide words):
#     vec_full_*.mem   first N_FULL test images with EVERY layer output (committed, small)
#     vec_1000_*.mem   first 1000 test images: input, 10 accumulators, digit, conf (git-ignored; regenerate)
#   Byte order inside a line: element 0 is the LEFTMOST byte pair. Layouts: see docs/QUANTIZATION.md.
#   int8 values are written as two's complement bytes, int32 as 8 hex digits.
#
# Usage:  .venv\Scripts\python.exe ml/export.py
# =============================================================================
import os

import numpy as np

import golden_int
from data_utils import load_mnist

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "export")
ROOT_SW = os.path.join(HERE, "..", "sw", "common")
N_FULL = 20
N_1000 = 1000


def hex8(a):
    return "".join(f"{int(v) & 0xFF:02x}" for v in np.asarray(a).reshape(-1))


def hex32(a):
    return "".join(f"{int(v) & 0xFFFFFFFF:08x}" for v in np.asarray(a).reshape(-1))


def write_lines(name, lines):
    with open(os.path.join(OUT, name), "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    os.makedirs(OUT, exist_ok=True)
    q = golden_int.load_params()

    # ---- weights and biases: one value per line --------------------------------
    for tag, w, b in (("l1", q["w1"], q["b1"]), ("l2", q["w2"], q["b2"]), ("fc", q["wf"], q["bf"])):
        write_lines(f"{tag}_w.mem", [f"{int(v) & 0xFF:02x}" for v in w.reshape(-1)])
        write_lines(f"{tag}_b.mem", [f"{int(v) & 0xFFFFFFFF:08x}" for v in b.reshape(-1)])

    # ---- requantization constants as a SystemVerilog include ---------------------
    svh = ["// Generated by ml/export.py from ml/quant_params.npz. Do not edit.",
           "// See docs/QUANTIZATION.md section 4/5.",
           "// Requantization:  y = clamp((acc * M + (1 << (S-1))) >>> S, 0, 255)"]
    for k in ("M1", "S1", "M2", "S2", "MC", "SC"):
        svh.append(f"localparam int QP_{k} = {int(q[k])};")
    write_lines("quant_params.svh", svh)

    # ---- the same constants as a SystemVerilog package (used by rtl/cnn_*.sv) -----
    pkg = ["// Generated by ml/export.py from ml/quant_params.npz. Do not edit.",
           "// Requantization constants, docs/QUANTIZATION.md section 4/5.",
           "package cnn_params_pkg;"]
    for k in ("M1", "S1", "M2", "S2", "MC", "SC"):
        pkg.append(f"    localparam int QP_{k} = {int(q[k])};")
    pkg.append("endpackage")
    write_lines("cnn_params_pkg.sv", pkg)

    # ---- wide ROMs for the accelerator (rtl/cnn_top.sv), one file per MAC count P --
    # Word = the weights of P output channels for one input index k, so one ROM read
    # feeds all P MACs. Bank p (bits [8p+7:8p]) = output channel og*P + p (0 if it does
    # not exist). Layer order: L1 (k = 0..8), L2 (k = 0..71), FC (k = 0..399); inside a
    # layer: word address = og * K + k. Bias ROM: one word of P x int32 per (layer, og).
    layers = [(q["w1"].reshape(8, 9), q["b1"]), (q["w2"].reshape(16, 72), q["b2"]),
              (q["wf"].reshape(10, 400), q["bf"])]
    for P in (1, 2, 4, 8, 16):
        wl, bl = [], []
        for w, b in layers:
            cout, K = w.shape
            for og in range((cout + P - 1) // P):
                outs = [og * P + p for p in reversed(range(P))]       # MSB = bank P-1
                for k in range(K):
                    wl.append("".join(f"{int(w[o, k]) & 0xFF:02x}" if o < cout else "00" for o in outs))
                bl.append("".join(f"{int(b[o]) & 0xFFFFFFFF:08x}" if o < cout else "00000000" for o in outs))
        write_lines(f"wrom_p{P}.mem", wl)
        write_lines(f"brom_p{P}.mem", bl)

    # ---- test vectors ----------------------------------------------------------
    _, _, xte, yte = load_mnist()
    res = golden_int.infer_batched(xte[:N_1000], q)

    full = slice(0, N_FULL)
    write_lines("vec_full_input.mem", [hex8(x) for x in xte[full]])
    write_lines("vec_full_l1.mem", [hex8(x) for x in res["l1"][full]])
    write_lines("vec_full_p1.mem", [hex8(x) for x in res["p1"][full]])
    write_lines("vec_full_l2.mem", [hex8(x) for x in res["l2"][full]])
    write_lines("vec_full_p2.mem", [hex8(x) for x in res["p2"][full]])
    write_lines("vec_full_acc.mem", [hex32(x) for x in res["acc"][full]])
    write_lines("vec_full_result.mem", [f"{int(d):x}{int(c):02x}" for d, c in zip(res["digit"][full], res["conf"][full])])

    write_lines("vec_1000_input.mem", [hex8(x) for x in xte[:N_1000]])
    write_lines("vec_1000_acc.mem", [hex32(x) for x in res["acc"]])
    write_lines("vec_1000_result.mem", [f"{int(d):x}{int(c):02x}" for d, c in zip(res["digit"], res["conf"])])
    write_lines("vec_1000_labels.mem", [f"{int(y):x}" for y in yte[:N_1000]])

    # ---- C header for the ARM self-test (sw/edge_ai_demo, injection mode) -------------
    hdr = ["/* Generated by ml/export.py. Do not edit.",
           " * First N MNIST test images with the golden-model result (docs/QUANTIZATION.md). */",
           "#ifndef MNIST_TEST_IMAGES_H", "#define MNIST_TEST_IMAGES_H", "",
           f"#define MNIST_N_TEST {N_FULL}", "",
           f"static const unsigned char mnist_img[{N_FULL}][784] = {{"]
    for x in xte[full]:
        vals = [str(int(v)) for v in x.reshape(-1)]
        hdr.append("  {" + ",".join(vals) + "},")
    hdr.append("};")
    hdr.append(f"static const unsigned char mnist_label[{N_FULL}]        = {{{','.join(str(int(v)) for v in yte[full])}}};")
    hdr.append(f"static const unsigned char mnist_golden_digit[{N_FULL}] = {{{','.join(str(int(v)) for v in res['digit'][full])}}};")
    hdr.append(f"static const unsigned char mnist_golden_conf[{N_FULL}]  = {{{','.join(str(int(v)) for v in res['conf'][full])}}};")
    hdr += ["", "#endif"]
    with open(os.path.join(ROOT_SW, "mnist_test_images.h"), "w") as f:
        f.write("\n".join(hdr) + "\n")

    acc1000 = (res["digit"] == yte[:N_1000]).mean()
    print(f"exported weights, constants and vectors to {OUT}")
    print(f"first {N_1000} test images: golden-model accuracy {acc1000 * 100:.1f} %")
    for f in sorted(os.listdir(OUT)):
        print(f"  {f:22s} {os.path.getsize(os.path.join(OUT, f)) / 1024:9.1f} KB")


if __name__ == "__main__":
    main()
