// Generated by ml/export.py from ml/quant_params.npz. Do not edit.
// Requantization constants, docs/QUANTIZATION.md section 4/5.
package cnn_params_pkg;
    localparam int QP_M1 = 20888;
    localparam int QP_S1 = 23;
    localparam int QP_M2 = 21182;
    localparam int QP_S2 = 23;
    localparam int QP_MC = 25098;
    localparam int QP_SC = 21;
endpackage
