// Generated by ml/export.py from ml/quant_params.npz. Do not edit.
// See docs/QUANTIZATION.md section 4/5.
// Requantization:  y = clamp((acc * M + (1 << (S-1))) >>> S, 0, 255)
localparam int QP_M1 = 20725;
localparam int QP_S1 = 23;
localparam int QP_M2 = 20000;
localparam int QP_S2 = 23;
localparam int QP_MC = 26807;
localparam int QP_SC = 21;
